# Generated by Django 5.1.15 on 2026-10-03 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StretcherTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stretcher_no', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stretcher_tags_held', to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stretcher_tags', to='core.clothroll')),
            ],
            options={
                'ordering': ['-checked_out_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('stretcher_no',), name='uniq_open_tag_per_stretcher'), models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('roll',), name='uniq_open_tag_per_roll')],
            },
        ),
    ]
